-- ═══════════════════════════════════════════════════════════════════════════
-- Migration 004 — AI daily insight, async report jobs, agent conversations
-- Safe to re-run: uses IF NOT EXISTS throughout.
-- ═══════════════════════════════════════════════════════════════════════════

-- Requires pgcrypto for gen_random_uuid() — enable if not already present
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ───────────────────────────────────────────────────────────────────────────
-- 1. daily_insight — one AI-generated insight per calendar day
--    Generated by a scheduled job at 07:00, read-only by the frontend.
-- ───────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS daily_insight (
    id           SERIAL      PRIMARY KEY,
    insight_date DATE        NOT NULL UNIQUE,
    generated_at TIMESTAMPTZ,
    status       VARCHAR(20) NOT NULL DEFAULT 'not_generated',
    -- not_generated | generating | generated | failed | stale
    text         TEXT,
    error        TEXT,
    model_used   VARCHAR(80),
    created_at   TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_daily_insight_date ON daily_insight(insight_date DESC);

-- ───────────────────────────────────────────────────────────────────────────
-- 2. report_job — async PDF generation jobs
-- ───────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS report_job (
    id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    offer_id     INT         REFERENCES offer(id) ON DELETE SET NULL,
    status       VARCHAR(20) NOT NULL DEFAULT 'queued',
    -- queued | processing | completed | failed
    progress     INT         DEFAULT 0 CHECK (progress BETWEEN 0 AND 100),
    file_path    TEXT,
    error        TEXT,
    created_at   TIMESTAMPTZ DEFAULT NOW(),
    updated_at   TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_report_job_status ON report_job(status);

-- ───────────────────────────────────────────────────────────────────────────
-- 3. agent_conversation — sidebar conversation metadata
--    thread_id maps to LangGraph PostgresSaver checkpoints.
-- ───────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS agent_conversation (
    id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    thread_id       VARCHAR(100) NOT NULL UNIQUE,
    title           TEXT,
    created_at      TIMESTAMPTZ DEFAULT NOW(),
    last_message_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_agent_conversation_last ON agent_conversation(last_message_at DESC);
